version: '3.3'
services:
  stock:
    image: "larueli/stock"
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=prod
      - APP_SECRET=CHANGEMEEEEEEEEEEE
      - DATABASE_URL=mysql://userStock:superSecretPasswordToChange@db:3306/stock
  db:
    image: "mariadb"
    restart: always
    volumes:
      - ./dbStorage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=superRootPasswordToChange
      - MYSQL_DATABASE=stock
      - MYSQL_USER=userStock
      - MYSQL_PASSWORD=superSecretPasswordToChange
